### ISSUE TITLE
Can't run getting started 

### ISSUE THREAD

**Issue by nakajo2011** [cryptoeconomicslab/plasma-chamber#192]
I get following errors when `yarn build`
$ yarn build
yarn run v1.13.0
$ yarn clean && truffle compile
$ rm -rf build/*
Error: Cannot find module 'truffle-hdwallet-provider'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/nakajo/work/ethereum-test/chaimber/chamber-packages/packages/chamber-contracts/truffle-config.js:21:26)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

My Environments: 
$ nvm version
v8.11.3
$ yarn -v
1.13.0

**Comment by syuhei176** [comment]
@nakajo2011 Are you still having a problem?

**Comment by nakajo2011** [comment]
Confirmed solved this issue. great!
I want to know did you what to solve this issue, if you ok.
