### ISSUE TITLE
Error at yarn cover

### ISSUE THREAD

**Issue by syuhei176** [cryptoeconomicslab/plasma-chamber#41]
Error occur at `yarn cover` in childchain.

```
$ cd childchain
$ yarn cover
yarn run v1.9.4
$ istanbul cover _mocha && istanbul-coveralls
Failed to parse file: /Users/syuhei/work/ethstacks/childchain/lib/tx.js
Transformation error; return original code
{ Error: Line 158: Unexpected token )
    at constructError (/Users/syuhei/work/ethstacks/node_modules/esprima/esprima.js:2407:21)
    at createError (/Users/syuhei/work/ethstacks/node_modules/esprima/esprima.js:2426:17)
    at unexpectedTokenError (/Users/syuhei/work/ethstacks/node_modules/esprima/esprima.js:2500:13)
    at throwUnexpectedToken (/Users/syuhei/work/ethstacks/node_modules/esprima/esprima.js:2505:15)
    at parsePrimaryExpression (/Users/syuhei/work/ethstacks/node_modules/esprima/esprima.js:3307:13)
    at inheritCoverGrammar (/Users/syuhei/work/ethstacks/node_modules/esprima/esprima.js:2681:18)
    at parseLeftHandSideExpressionAllowCall (/Users/syuhei/work/ethstacks/node_modules/esprima/esprima.js:3414:20)
```

**Comment by syuhei176** [comment]
@onokatio Is this chamber repo?

> /home/katio/script/cryptoeconomics/PlasmaVM-JS/node_modules/istanbul-coveralls/cli.js:33

**Comment by onokatio** [comment]
> @onokatio Is this chamber repo?
> 
> > /home/katio/script/cryptoeconomics/PlasmaVM-JS/node_modules/istanbul-coveralls/cli.js:33

yes
